"""
Django settings for inventory project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import logging
from pathlib import Path
import os
from django.contrib.messages import constants as messages
from dotenv import load_dotenv

load_dotenv()

# ✅ MESSAGE CONFIGURATION
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MESSAGE_LEVEL = messages.DEBUG

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger error',
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Secret key loaded from .env file (never hardcode in production)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback-for-dev-only')

# Debug mode controlled by .env file — defaults to False (production-safe).
# Set DJANGO_DEBUG=true in your local .env for development.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
}

USE_L10N = False
DATE_INPUT_FORMATS = ['%d-%m-%Y', '%Y-%m-%d']

ALLOWED_HOSTS = ['192.168.0.15', 'localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
   'app',
   'django.contrib.admin',
   'django.contrib.auth',
   'django.contrib.contenttypes',
   'django.contrib.sessions',
   'django.contrib.messages',
   'django.contrib.staticfiles',
   'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Required for POST-based logout
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'app.middleware.ConcurrentSessionMiddleware',
    'app.middleware.PageLockMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'app.context_processors.nav_badges',
                'app.context_processors.page_lock',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory.wsgi.application'

# ============================================
# HTTPS / TLS HARDENING
# ============================================
# The app itself is served by waitress over plain HTTP on 127.0.0.1:8000.
# TLS is terminated by a reverse proxy (see Caddyfile) that forwards to it.
#
# These secure settings are GATED behind DJANGO_SECURE so that enabling them
# does NOT break a plain-HTTP LAN deployment. Turn them on ONLY once the HTTPS
# proxy is actually in front of the app:
#     set DJANGO_SECURE=1   (and run Caddy — see DEPLOYMENT_HTTPS.md)
SECURE = os.environ.get('DJANGO_SECURE', 'False').lower() in ('1', 'true', 'yes')

if SECURE:
    # Trust the X-Forwarded-Proto header set by the reverse proxy (Caddy/nginx)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Redirect any plain HTTP that reaches Django to HTTPS
    SECURE_SSL_REDIRECT = True
    # Only send cookies over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS — tell browsers to always use HTTPS for this host
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Misc hardening
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # JS-read CSRF token still needed by the app
    # Origins Django will accept for CSRF over HTTPS (comma-separated env override)
    CSRF_TRUSTED_ORIGINS = [
        o.strip() for o in os.environ.get(
            'DJANGO_CSRF_TRUSTED_ORIGINS',
            'https://192.168.0.15,https://localhost'
        ).split(',') if o.strip()
    ]
else:
    # Plain-HTTP LAN mode (default) — keep cookies usable over HTTP
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

SESSION_COOKIE_AGE = 28800  # 8 hours — auto-expire after a pharmacy shift

# Concurrent session limits (by role)
MAX_SESSIONS_STAFF = 1        # Admin accounts (GINA) — new login replaces old
MAX_SESSIONS_REGULAR = 5      # Regular accounts (PU) — 6th login blocked

# Admin passkey — lets a regular (PU) user temporarily unlock admin-only
# functions for their session by entering this key. ALWAYS override via env
# in production; the default below is only for local/dev use.
ADMIN_PASSKEY = os.environ.get('ADMIN_PASSKEY', 'pharmacy-admin')
# How long (seconds) a passkey unlock stays valid before a restricted page
# re-prompts. Default 300 = 5-minute window (absolute, from unlock time).
# Set to 0 to make an unlock last until logout / session end.
ADMIN_PASSKEY_TTL = int(os.environ.get('ADMIN_PASSKEY_TTL', '300'))


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
   {
       'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
   },
   {
       'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
   },
   {
       'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
   },
   {
       'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
   },
]

LOGIN_URL = '/login/'  # Redirect unauthenticated users to the login page
LOGIN_REDIRECT_URL = '/'  # Redirect after successful login
LOGOUT_REDIRECT_URL = '/login/'  # Redirect after logout

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Canada/Eastern'

USE_I18N = True

USE_TZ = True  # Keep this enabled to support timezones


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# settings.py
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# AUTHENTICATION BACKENDS
# ============================================
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ============================================
# BRUTE-FORCE PROTECTION (django-axes)
# ============================================
AXES_FAILURE_LIMIT = 5              # Lock after 5 failed login attempts
AXES_COOLOFF_TIME = 0.5             # Lock for 30 minutes (0.5 hours)
AXES_LOCKOUT_PARAMETERS = ['ip_address']
AXES_RESET_ON_SUCCESS = True        # Reset failed count after successful login

# ============================================
# EMAIL (daily report digest)
# Wired to send to anguscwebsite@gmail.com. Delivery is INERT until a sending
# account is configured: set EMAIL_HOST_USER + EMAIL_HOST_PASSWORD (a Gmail
# "app password", NOT the normal password) in the environment. Once those are
# present the backend auto-switches from console (prints only) to real SMTP.
# ============================================
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_USER
    else 'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'Pharmacy Inventory <noreply@pharmacy.local>'
)

# Recipients of the daily end-of-day report (comma-separated env var).
DAILY_REPORT_RECIPIENTS = [
    e.strip() for e in os.environ.get('DAILY_REPORT_RECIPIENTS', 'anguscwebsite@gmail.com').split(',') if e.strip()
]
