# Generated by Django 6.0.2 on 2026-02-21 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('xxsmall', 'XX-Small'), ('xsmall', 'X-Small'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'X-Large'), ('xxlarge', 'XX-Large'), ('na', 'N/A'), ('Bathroom', 'Bathroom')], max_length=100)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('na', 'N/A'), ('Bathroom', 'Bathroom')], max_length=100)),
                ('item_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('item_number', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('unit_size', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('taxable', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('stock_bought', models.IntegerField(default=0)),
                ('stock_sold', models.IntegerField(default=0)),
                ('stock_expired', models.IntegerField(default=0)),
                ('stock_unfulfilled', models.IntegerField(default=0)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
                ('previous_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revert_products', to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('od_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyPurchasedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('checkin', 'Stock Added'), ('checkout', 'Stock Removed (Sale)'), ('checkout_unfulfilled', 'Unfulfilled Sale (Stockout)'), ('expired', 'Expired Stock'), ('error_add', 'Manual Addition'), ('error_subtract', 'Manual Adjustment'), ('checkin_delete1', 'Stock Removed via Delete Button'), ('deletion', 'Product Deletion'), ('return', 'Customer Return')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_changes', to='app.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode',), name='uniq_product_barcode_not_null'),
        ),
    ]
