# Generated by Django 6.0.3 on 2026-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'indexes': [models.Index(fields=['barcode'], name='delivery_barcode_idx'), models.Index(fields=['checked_in_at'], name='delivery_checkin_date_idx')],
            },
        ),
    ]
