# Generated by Django 6.0.6 on 2026-06-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_checkin_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinsession',
            name='scanned_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
