# Generated by Django 6.0.6 on 2026-06-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_checkin_session_scanned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinsession',
            name='inventory_mode',
            field=models.BooleanField(default=False),
        ),
    ]
