# Generated by Django 6.0.6 on 2026-06-05 03:58

from django.db import migrations, models


def backfill_scanned_by(apps, schema_editor):
    """Set scanned_by to username for existing rows where it's NULL or empty."""
    CheckinSession = apps.get_model('app', 'CheckinSession')
    for session in CheckinSession.objects.filter(models.Q(scanned_by__isnull=True) | models.Q(scanned_by='')):
        session.scanned_by = session.user.username if session.user_id else 'Unknown'
        session.save(update_fields=['scanned_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_checkin_session_inventory_mode'),
    ]

    operations = [
        # 1. Backfill NULLs with the username
        migrations.RunPython(backfill_scanned_by, migrations.RunPython.noop),
        # 2. Update the field to allow blank and set DB default
        migrations.AlterField(
            model_name='checkinsession',
            name='scanned_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
