# Generated by Django 5.1.3 on 2025-02-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
