# Generated by Django 5.2.4 on 2026-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_label_queue_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
