# Generated by Django 6.0.6 on 2026-06-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_category_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinsession',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
