# Generated by Django 5.2.4 on 2026-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_useraction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycheckin',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
