# Generated by Django 5.2.4 on 2026-06-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_delivery_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExpiryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_dates', to='app.product')),
            ],
            options={
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['product', 'expiry_date'], name='prodexpiry_prod_date_idx')],
            },
        ),
    ]
