# Generated by Django 5.2.4 on 2026-06-08 16:10

from django.db import migrations


def copy_expiry_dates_forward(apps, schema_editor):
    Product = apps.get_model('app', 'Product')
    ProductExpiryDate = apps.get_model('app', 'ProductExpiryDate')
    rows = []
    for p in Product.objects.exclude(expiry_date__isnull=True):
        rows.append(ProductExpiryDate(product=p, expiry_date=p.expiry_date))
    ProductExpiryDate.objects.bulk_create(rows)


def copy_expiry_dates_backward(apps, schema_editor):
    ProductExpiryDate = apps.get_model('app', 'ProductExpiryDate')
    ProductExpiryDate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_product_expiry_date_model'),
    ]

    operations = [
        migrations.RunPython(copy_expiry_dates_forward, copy_expiry_dates_backward),
    ]
