# Generated by Django 6.0.6 on 2026-06-15 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('delete_product', 'Deleted Product'), ('delete_order', 'Deleted Order'), ('delete_all_orders', 'Deleted All Orders'), ('delete_recently_purchased', 'Deleted Recently Purchased'), ('delete_all_recently_purchased', 'Deleted All Recently Purchased'), ('bulk_delete_recently_purchased', 'Bulk Deleted Recently Purchased'), ('submit_order', 'Submitted Order'), ('add_product', 'Added New Product'), ('start_session', 'Started Check-in Session'), ('end_session', 'Ended Check-in Session'), ('reopen_session', 'Reopened Check-in Session'), ('adjust_session_line', 'Adjusted Session Line'), ('remove_session_line', 'Removed Session Line'), ('delete_session', 'Deleted Check-in Session'), ('clear_session_history', 'Cleared Session History'), ('delivery_checkin', 'Delivery Check-in'), ('delivery_checkout', 'Delivery Check-out'), ('delivery_undo_checkout', 'Delivery Undo Check-out'), ('delivery_clear_history', 'Delivery Cleared History'), ('edit_product', 'Edited Product'), ('update_product_settings', 'Updated Product Settings'), ('revert_label_category', 'Reverted Label Categories'), ('create_account', 'Created Account'), ('clear_label_queue', 'Cleared Label Queue'), ('delete_item_list', 'Deleted Item List Entry'), ('add_item_list', 'Added Item List Entry'), ('delivery_delete_record', 'Deleted Delivery Record'), ('cycle_count', 'Cycle Count Completed'), ('retire_expired', 'Retired Expired Stock'), ('print_labels', 'Printed Labels'), ('delete_label_session', 'Deleted Label Session'), ('regenerate_label_session', 'Regenerated Label Session'), ('clear_all_label_sessions', 'Cleared All Label Sessions'), ('checkout_submit', 'Submitted PU Checkout'), ('checkout_new', 'Started New PU Checkout')], max_length=50),
        ),
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('active_session_key', models.CharField(blank=True, default='', max_length=40)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_barcode', models.CharField(blank=True, default='', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.checkoutorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='checkoutorder',
            index=models.Index(fields=['user', 'status'], name='checkout_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutorder',
            index=models.Index(fields=['-created_at'], name='checkout_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkoutorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('user',), name='uniq_active_checkout_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='checkoutorderitem',
            unique_together={('checkout', 'product')},
        ),
    ]
