# Generated by Django 6.0.6 on 2026-06-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_usersession_ip_address_usersession_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
