# Generated by Django 6.0.6 on 2026-06-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_useraction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_giveaway',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='change_type',
            field=models.CharField(choices=[('checkin', 'Stock Added'), ('checkout', 'Stock Removed (Sale)'), ('checkout_unfulfilled', 'Unfulfilled Sale (Stockout)'), ('expired', 'Expired Stock'), ('error_add', 'Manual Addition'), ('error_subtract', 'Manual Adjustment'), ('checkin_delete1', 'Stock Removed via Delete Button'), ('deletion', 'Product Deletion'), ('return', 'Customer Return'), ('giveaway', 'Giveaway (Terminal)'), ('giveaway_unfulfilled', 'Unfulfilled Giveaway')], max_length=30),
        ),
    ]
