# Generated by Django 6.0.6 on 2026-06-16 01:48
#
# One-time backfill: historical PU terminal checkouts were recorded as
# 'checkout' / 'checkout_unfulfilled' (same as POS sales). Reclassify them to
# 'giveaway' / 'giveaway_unfulfilled' so they stop counting as sales demand,
# and move their cumulative counters from stock_sold/stock_unfulfilled to
# stock_giveaway. Terminal rows are identified by their note ("PU Checkout ...").

from django.db import migrations
from django.db.models import F, Sum


def _shift_counters(Product, qs, from_field, to_field=None):
    """Move the per-product summed quantity off `from_field` (and onto `to_field` if given)."""
    totals = list(qs.values('product_id').annotate(total=Sum('quantity')))
    for row in totals:
        qty = abs(row['total'] or 0)
        if not qty:
            continue
        updates = {from_field: F(from_field) - qty}
        if to_field:
            updates[to_field] = F(to_field) + qty
        Product.objects.filter(pk=row['product_id']).update(**updates)


def forward(apps, schema_editor):
    StockChange = apps.get_model('app', 'StockChange')
    Product = apps.get_model('app', 'Product')

    fulfilled = StockChange.objects.filter(change_type='checkout', note__startswith='PU Checkout')
    _shift_counters(Product, fulfilled, 'stock_sold', 'stock_giveaway')
    fulfilled.update(change_type='giveaway')

    unfulfilled = StockChange.objects.filter(change_type='checkout_unfulfilled', note__startswith='PU Checkout')
    _shift_counters(Product, unfulfilled, 'stock_unfulfilled')  # giveaway_unfulfilled has no counter
    unfulfilled.update(change_type='giveaway_unfulfilled')


def backward(apps, schema_editor):
    StockChange = apps.get_model('app', 'StockChange')
    Product = apps.get_model('app', 'Product')

    fulfilled = StockChange.objects.filter(change_type='giveaway', note__startswith='PU Checkout')
    _shift_counters(Product, fulfilled, 'stock_giveaway', 'stock_sold')
    fulfilled.update(change_type='checkout')

    unfulfilled = StockChange.objects.filter(change_type='giveaway_unfulfilled', note__startswith='PU Checkout')
    totals = list(unfulfilled.values('product_id').annotate(total=Sum('quantity')))
    for row in totals:
        qty = abs(row['total'] or 0)
        if qty:
            Product.objects.filter(pk=row['product_id']).update(stock_unfulfilled=F('stock_unfulfilled') + qty)
    unfulfilled.update(change_type='checkout_unfulfilled')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_product_stock_giveaway_alter_stockchange_change_type'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
