# Generated by Django 6.0.6 on 2026-06-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_reclassify_pu_checkout_as_giveaway'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkoutorder',
            name='uniq_active_checkout_per_user',
        ),
    ]
