# Generated by Django 6.0.6 on 2026-06-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_checkoutorder_uniq_active_checkout_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='change_type',
            field=models.CharField(choices=[('checkin', 'Stock Added'), ('checkout', 'Stock Removed (Sale)'), ('checkout_unfulfilled', 'Unfulfilled Sale (Stockout)'), ('expired', 'Expired Stock'), ('error_add', 'Manual Addition'), ('error_subtract', 'Manual Adjustment'), ('checkin_delete1', 'Stock Removed via Delete Button'), ('deletion', 'Product Deletion'), ('return', 'Customer Return'), ('giveaway', 'No Sale (Terminal)'), ('giveaway_unfulfilled', 'Unfulfilled No Sale')], max_length=30),
        ),
    ]
