# Generated by Django 6.0.6 on 2026-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_pagepresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='current_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
