# Generated by Django 6.0.6 on 2026-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_usersession_current_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='draft_cart',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
