# Generated by Django 5.2.4 on 2026-06-18 17:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_product_snapshots(apps, schema_editor):
    """Populate the new snapshot fields from each row's still-present product."""
    StockChange = apps.get_model('app', 'StockChange')
    batch = []
    qs = StockChange.objects.filter(product__isnull=False).select_related('product')
    for sc in qs.iterator():
        sc.product_name = sc.product.name or ''
        sc.product_barcode = sc.product.barcode or ''
        batch.append(sc)
        if len(batch) >= 1000:
            StockChange.objects.bulk_update(batch, ['product_name', 'product_barcode'])
            batch = []
    if batch:
        StockChange.objects.bulk_update(batch, ['product_name', 'product_barcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_order_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='product_barcode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RunPython(backfill_product_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockchange',
            name='change_type',
            field=models.CharField(choices=[('checkin', 'Stock Added'), ('checkout', 'Stock Removed (Sale)'), ('checkout_unfulfilled', 'Unfulfilled Sale (Stockout)'), ('expired', 'Expired Stock'), ('error_add', 'Manual Addition'), ('error_subtract', 'Manual Adjustment'), ('checkin_delete1', 'Stock Removed via Delete Button'), ('deletion', 'Product Deletion'), ('giveaway', 'No Sale (Terminal)'), ('giveaway_unfulfilled', 'Unfulfilled No Sale')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to='app.product'),
        ),
    ]
