# Generated by Django 5.2.4 on 2026-06-18 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_fix_product_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('delete_product', 'Deleted Product'), ('delete_order', 'Deleted Order'), ('delete_all_orders', 'Deleted All Orders'), ('delete_recently_purchased', 'Deleted Recently Purchased'), ('delete_all_recently_purchased', 'Deleted All Recently Purchased'), ('bulk_delete_recently_purchased', 'Bulk Deleted Recently Purchased'), ('submit_order', 'Submitted Order'), ('add_product', 'Added New Product'), ('start_session', 'Started Check-in Session'), ('end_session', 'Ended Check-in Session'), ('reopen_session', 'Reopened Check-in Session'), ('adjust_session_line', 'Adjusted Session Line'), ('remove_session_line', 'Removed Session Line'), ('delete_session', 'Deleted Check-in Session'), ('clear_session_history', 'Cleared Session History'), ('delivery_checkin', 'Delivery Check-in'), ('delivery_checkout', 'Delivery Check-out'), ('delivery_undo_checkout', 'Delivery Undo Check-out'), ('delivery_clear_history', 'Delivery Cleared History'), ('edit_product', 'Edited Product'), ('update_product_settings', 'Updated Product Settings'), ('revert_label_category', 'Reverted Label Categories'), ('create_account', 'Created Account'), ('passkey_unlock', 'Unlocked Admin Passkey'), ('clear_label_queue', 'Cleared Label Queue'), ('delete_item_list', 'Deleted Item List Entry'), ('add_item_list', 'Added Item List Entry'), ('delivery_delete_record', 'Deleted Delivery Record'), ('cycle_count', 'Cycle Count Completed'), ('retire_expired', 'Retired Expired Stock'), ('print_labels', 'Printed Labels'), ('delete_label_session', 'Deleted Label Session'), ('regenerate_label_session', 'Regenerated Label Session'), ('clear_all_label_sessions', 'Cleared All Label Sessions'), ('checkout_submit', 'Submitted PU Checkout'), ('checkout_new', 'Started New PU Checkout'), ('ordering_status_update', 'Updated Ordering Sheet Status'), ('ordering_delete', 'Removed Ordering Sheet Entry')], max_length=50),
        ),
        migrations.CreateModel(
            name='OrderingSheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reasoning', models.CharField(choices=[('stock', 'Order for stock'), ('basket', 'Order for basket'), ('one_remaining', '1 remaining')], max_length=20)),
                ('quantity_remaining', models.CharField(blank=True, max_length=50)),
                ('urgency', models.CharField(choices=[('low', 'Low (1 week PU)'), ('medium', 'Medium (4 days PU)'), ('high', 'High (TOMORROW PU)')], default='low', max_length=10)),
                ('initials', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('backordered', 'Back-Ordered'), ('ordered', 'Ordered'), ('not_for_sale', 'Not for Sale')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordering_entries', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordering_deletions', to=settings.AUTH_USER_MODEL)),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordering_status_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', 'status'], name='app_orderin_is_dele_1807e6_idx')],
            },
        ),
    ]
