# Generated by Django 5.2.4 on 2026-06-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_useraction_action_orderingsheetentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingsheetentry',
            name='order_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
