# Generated by Django 5.2.4 on 2026-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_orderingsheetentry_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingsheetentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('backordered', 'Back-Ordered'), ('ordered', 'Ordered'), ('not_for_sale', 'Not for Sale (Consult Pharmacist)')], default='pending', max_length=20),
        ),
    ]
