# Generated by Django 5.2.4 on 2026-06-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_orderingsheetentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_barcode', models.CharField(blank=True, default='', max_length=64)),
                ('expected_qty', models.IntegerField(default=0)),
                ('counted_qty', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_count_lines', to='app.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_lines', to='app.checkinsession')),
            ],
            options={
                'ordering': ['product_name'],
                'unique_together': {('session', 'product')},
            },
        ),
    ]
