# Generated by Django 5.2.4 on 2026-06-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_inventorycountline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingsheetentry',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderingsheetentry',
            name='quantity_needed',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
