# Generated by Django 5.2.4 on 2026-06-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_orderingsheetentry_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingsheetentry',
            name='reasoning',
            field=models.CharField(choices=[('stock', 'Order for stock'), ('basket', 'Order for basket'), ('expiring', 'Expiring')], max_length=20),
        ),
    ]
