# Generated by Django 5.2.4 on 2026-06-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_orderingsheetentry_reasoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingsheetentry',
            name='urgency',
            field=models.CharField(choices=[('high', 'High (TOMORROW PU)'), ('medium', 'Medium (4 days PU)'), ('low', 'Low (1 week PU)'), ('na', 'N/A')], default='low', max_length=10),
        ),
    ]
