# Generated by Django 5.2.4 on 2026-06-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_orderingsheetentry_urgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('pdf', models.BinaryField()),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
