# Generated by Django 6.0.6 on 2026-06-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_order_seniors_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='expiry_at_sale',
            field=models.DateField(blank=True, null=True),
        ),
    ]
