# Generated by Django 6.0.6 on 2026-06-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_orderdetail_expiry_at_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(choices=[('computer', 'Computer'), ('phone', 'Phone')], default='computer', max_length=10),
        ),
    ]
