# Generated by Django 6.0.6 on 2026-07-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_useraction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='hidden_from_history',
            field=models.BooleanField(default=False),
        ),
    ]
