# Generated by Django 6.0.6 on 2026-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_checkoutorder_hidden_from_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingsheetentry',
            name='gsheet_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderingsheetentry',
            name='source',
            field=models.CharField(choices=[('app', 'App'), ('gsheet', 'Google Sheet')], default='app', max_length=10),
        ),
    ]
