# Generated by Django 6.0.6 on 2026-07-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_useraction_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
