# Generated by Django 5.2.4 on 2026-08-13 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsessionitem',
            name='custom_lines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labelsessionitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomLabelQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_label_queue_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at', 'pk'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='customlabel_user_added_idx')],
            },
        ),
    ]
