# Generated by Django 5.2.4 on 2026-08-13 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_persist_custom_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='draft_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_timer_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='timer_reset_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SupplierOrderPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_sequence', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_order_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.supplierorderplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('mck', 'McKesson'), ('kf', 'Kohl & Frisch')], max_length=3)),
                ('sequence_position', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('starting', 'Starting'), ('login', 'Login required'), ('waiting_user', 'Waiting for user'), ('running', 'Running'), ('paused', 'Paused'), ('review', 'Ready for review'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='starting', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('current', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pause_requested', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_order_runs', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='app.supplierorderplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('quantity_requested', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('added', 'Added'), ('skipped', 'Not added')], default='pending', max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.supplierorderrun')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DashboardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_tasks_archived', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['archived_at', 'completed', '-created_at'], name='dashtask_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabelPrintOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('barcode_overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_print_overrides', to='app.product')),
                ('queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_overrides', to='app.labelqueueitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_print_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-updated_at'], name='labeloverride_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('queue_item__isnull', True)), models.Q(('product__isnull', True), ('queue_item__isnull', False)), _connector='OR'), name='labeloverride_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='labeloverride_user_product_uniq'), models.UniqueConstraint(condition=models.Q(('queue_item__isnull', False)), fields=('user', 'queue_item'), name='labeloverride_user_queue_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='supplierorderplan',
            index=models.Index(fields=['status', '-created_at'], name='supplierplan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorderplan',
            index=models.Index(fields=['created_by', '-created_at'], name='supplierplan_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'position'), name='supplierplanitem_position_uniq'),
        ),
        migrations.AddIndex(
            model_name='supplierorderrun',
            index=models.Index(fields=['vendor', 'state', '-created_at'], name='supplierrun_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorderrun',
            index=models.Index(fields=['plan', 'sequence_position'], name='supplierrun_plan_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderrun',
            constraint=models.UniqueConstraint(condition=models.Q(('plan__isnull', False)), fields=('plan', 'vendor'), name='supplierrun_plan_vendor_uniq'),
        ),
        migrations.AddIndex(
            model_name='supplierorderrunitem',
            index=models.Index(fields=['run', 'outcome'], name='supplierrunitem_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorderrunitem',
            index=models.Index(fields=['product', 'outcome'], name='supplierrunitem_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderrunitem',
            constraint=models.UniqueConstraint(fields=('run', 'position'), name='supplierrunitem_position_uniq'),
        ),
    ]
