# Generated by Django 5.2.4 on 2026-08-14 00:29

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


MONEY = Decimal('0.01')
TAX_RATE = Decimal('0.13')


def backfill_purchase_financial_snapshots(apps, schema_editor):
    Order = apps.get_model('app', 'Order')
    OrderDetail = apps.get_model('app', 'OrderDetail')

    details = list(
        OrderDetail.objects.filter(order__submitted=True).select_related('product')
    )
    for detail in details:
        product = detail.product
        if product is not None:
            # These are the best values recoverable for legacy transactions.
            # The parent order is marked "backfilled" so downstream consumers
            # can distinguish them from exact future sale-time captures.
            detail.taxable_at_sale = product.taxable
            detail.cost_per_unit_at_sale = product.price_per_unit
    if details:
        OrderDetail.objects.bulk_update(
            details, ['taxable_at_sale', 'cost_per_unit_at_sale'], batch_size=500,
        )

    for order in Order.objects.filter(submitted=True).prefetch_related('details').iterator(
        chunk_size=200,
    ):
        subtotal = Decimal('0.00')
        taxable_subtotal = Decimal('0.00')
        for detail in order.details.all():
            line_total = detail.price * detail.quantity
            subtotal += line_total
            if detail.taxable_at_sale is True:
                taxable_subtotal += line_total

        subtotal = subtotal.quantize(MONEY, rounding=ROUND_HALF_UP)
        discount = Decimal('0.00')
        taxable_base = taxable_subtotal
        if order.seniors_discount:
            discount = (subtotal * Decimal('0.10')).quantize(MONEY, rounding=ROUND_HALF_UP)
            taxable_base = taxable_subtotal * Decimal('0.90')
        tax = (taxable_base * TAX_RATE).quantize(MONEY, rounding=ROUND_HALF_UP)

        order.subtotal = subtotal
        order.discount_amount = discount
        order.tax = tax
        order.tax_rate = TAX_RATE
        order.total_price = (subtotal - discount + tax).quantize(MONEY, rounding=ROUND_HALF_UP)
        order.financial_snapshot_source = 'backfilled'
        order.save(update_fields=[
            'subtotal', 'discount_amount', 'tax', 'tax_rate', 'total_price',
            'financial_snapshot_source',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_import_legacy_supplier_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='financial_snapshot_source',
            field=models.CharField(blank=True, choices=[('captured', 'Captured at sale'), ('backfilled', 'Backfilled from available history')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1300'), max_digits=6),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='cost_per_unit_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='taxable_at_sale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(
            backfill_purchase_financial_snapshots,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'quantity_in_stock'], name='product_stock_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='product_cat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['expiry_date'], name='product_expiry_idx'),
        ),
    ]
