# Generated by Django 5.2.4 on 2026-08-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_useraction_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=100)),
                ('table_key', models.CharField(default='main', max_length=100)),
                ('density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=12)),
                ('page_size', models.PositiveSmallIntegerField(choices=[(25, '25 rows'), (50, '50 rows'), (100, '100 rows'), (200, '200 rows')], default=50)),
                ('hidden_columns', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page_key', 'table_key'],
                'indexes': [models.Index(fields=['user', 'page_key'], name='tablepref_user_page_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'page_key', 'table_key'), name='user_table_preference_uniq'), models.CheckConstraint(condition=models.Q(('page_size__in', [25, 50, 100, 200])), name='user_table_page_size_allowed')],
            },
        ),
    ]
