# Generated by Django 5.2.4 on 2026-08-16

from datetime import time

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_default_store_hours(apps, schema_editor):
    StoreHours = apps.get_model('app', 'StoreHours')
    rows = [
        (0, time(9, 30), time(18, 0), False),
        (1, time(9, 30), time(19, 0), False),
        (2, time(9, 30), time(18, 0), False),
        (3, time(9, 30), time(19, 0), False),
        (4, time(9, 30), time(18, 0), False),
        (5, time(9, 30), time(16, 0), False),
        (6, None, None, True),
    ]
    StoreHours.objects.bulk_create([
        StoreHours(
            weekday=weekday,
            opens_at=opens_at,
            closes_at=closes_at,
            is_closed=is_closed,
        )
        for weekday, opens_at, closes_at, is_closed in rows
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_usertablepreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('issues', 'Problems found'), ('repaired', 'Problems repaired'), ('error', 'Audit failed')], default='running', max_length=12)),
                ('repair_requested', models.BooleanField(default=False)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('repaired_count', models.PositiveIntegerField(default=0)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-started_at', '-pk']},
        ),
        migrations.CreateModel(
            name='InventoryAuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='error', max_length=10)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('expected_value', models.CharField(blank=True, default='', max_length=100)),
                ('actual_value', models.CharField(blank=True, default='', max_length=100)),
                ('repairable', models.BooleanField(default=False)),
                ('repaired', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_issues', to='app.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='app.inventoryauditrun')),
            ],
            options={'ordering': ['severity', 'code', 'pk']},
        ),
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(choices=[('gsheet_preclose', 'Google Sheet pre-closing pull'), ('report_cleanup', 'Daily report archive cleanup')], max_length=40)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=12)),
                ('business_date', models.DateField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Successful'), ('error', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_job_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-started_at', '-pk']},
        ),
        migrations.CreateModel(
            name='StoreHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Store hours',
                'ordering': ['weekday'],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='storehours_weekday_valid'),
                    models.CheckConstraint(condition=models.Q(('is_closed', True), models.Q(('closes_at__gt', models.F('opens_at')), ('closes_at__isnull', False), ('opens_at__isnull', False)), _connector='OR'), name='storehours_open_times_valid'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryauditrun',
            index=models.Index(fields=['status', '-started_at'], name='invaudit_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditissue',
            index=models.Index(fields=['run', 'code'], name='auditissue_run_code_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditissue',
            index=models.Index(fields=['product', '-created_at'], name='auditissue_product_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobrun',
            index=models.Index(fields=['job_key', 'status', '-started_at'], name='jobrun_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobrun',
            index=models.Index(fields=['trigger', '-started_at'], name='jobrun_trigger_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledjobrun',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger', 'scheduled')), fields=('job_key', 'business_date'), name='scheduled_job_once_per_day'),
        ),
        migrations.AddConstraint(
            model_name='scheduledjobrun',
            constraint=models.CheckConstraint(condition=models.Q(('trigger', 'manual'), ('business_date__isnull', False), _connector='OR'), name='scheduled_job_date_required'),
        ),
        migrations.RunPython(create_default_store_hours, migrations.RunPython.noop),
    ]
