# Generated by Django 5.2.4 on 2026-08-19 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_add_preclosing_backup_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinReceivingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('lot_expiry', models.DateField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('existing_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_receiving_drafts', to='app.productlot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_receiving_drafts', to='app.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_drafts', to='app.checkinsession')),
            ],
            options={
                'ordering': ['-updated_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('session', 'product'), name='checkin_receiving_draft_session_product_uniq')],
            },
        ),
    ]
