# Generated by Django 5.2.4 on 2026-09-08 06:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_ordering_custom_status_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name', 'brand', 'strength'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Upper(models.F('name')))), name='prescription_drug_name_uppercase'), models.CheckConstraint(condition=models.Q(('brand', django.db.models.functions.text.Upper(models.F('brand')))), name='prescription_drug_brand_uppercase')],
            },
        ),
    ]
