# Generated by Django 5.2.4 on 2026-09-08 06:56

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_prescription_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDrugLearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('parser_version', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.CharField(blank=True, choices=[('missing_brand', 'Brand missing or unrecognized'), ('missing_strength', 'Strength missing or units unclear'), ('ambiguous', 'More than one possible interpretation'), ('invalid_name', 'Drug name could not be separated'), ('invalid_details', 'Details do not pass catalogue validation')], max_length=40)),
                ('processed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-processed_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrug',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('brand')), django.db.models.functions.text.Lower(django.db.models.functions.text.Replace(django.db.models.functions.text.Trim('strength'), models.Value(' '), models.Value(''))), name='uniq_prescription_drug_identity'),
        ),
        migrations.AddField(
            model_name='prescriptiondruglearningrecord',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_records', to='app.prescriptiondrug'),
        ),
        migrations.AddField(
            model_name='prescriptiondruglearningrecord',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_learning', to='app.orderingsheetentry'),
        ),
    ]
