# Generated by Django 5.2.4 on 2026-09-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_prescription_drug_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDrugRequestRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='pack_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='request_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='total_quantity_needed',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='unknown_quantity_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='prescriptiondruglearningrecord',
            name='quantity_needed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondruglearningrecord',
            name='quantity_unit',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='prescriptiondruglearningrecord',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondruglearningrecord',
            name='source_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='prescriptiondruglearningrecord',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_learning', to='app.orderingsheetentry'),
        ),
        migrations.AlterField(
            model_name='prescriptiondruglearningrecord',
            name='reason',
            field=models.CharField(blank=True, choices=[('missing_brand', 'Brand missing or unrecognized'), ('missing_strength', 'Strength missing or units unclear'), ('ambiguous', 'More than one possible interpretation'), ('invalid_name', 'Drug name could not be separated'), ('invalid_details', 'Details do not pass catalogue validation'), ('ineligible_source', 'Source is no longer a drug request')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondruglearningrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_needed__isnull', True), ('quantity_needed__gte', 0), _connector='OR'), name='prescription_request_qty_nonnegative'),
        ),
        migrations.AddField(
            model_name='prescriptiondrugrequestrevision',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_revisions', to='app.prescriptiondrug'),
        ),
        migrations.AddField(
            model_name='prescriptiondrugrequestrevision',
            name='learning_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='app.prescriptiondruglearningrecord'),
        ),
    ]
