# Generated by Django 5.2.4 on 2026-09-08 07:37

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def preserve_existing_catalogue(apps, schema_editor):
    Drug = apps.get_model('app', 'PrescriptionDrug')
    Package = apps.get_model('app', 'PrescriptionDrugPackage')
    Record = apps.get_model('app', 'PrescriptionDrugLearningRecord')
    Change = apps.get_model('app', 'PrescriptionDrugChange')
    database = schema_editor.connection.alias
    learned_ids = Record.objects.using(database).exclude(drug_id=None).values('drug_id')
    Drug.objects.using(database).filter(pk__in=learned_ids).update(source='ordering_sheet')
    for drug in Drug.objects.using(database).exclude(pack_size='').iterator():
        package = Package.objects.using(database).create(drug_id=drug.pk, label=drug.pack_size)
        Change.objects.using(database).create(
            drug_id=drug.pk, entity_type='package', entity_id=package.pk,
            action='imported', actor_label='Existing catalogue',
            before={}, after={'label': package.label},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_prescription_drug_quantities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDrugChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=16)),
                ('entity_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=16)),
                ('actor_label', models.CharField(max_length=150)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDrugPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(blank=True, default='', max_length=24)),
                ('upc', models.CharField(blank=True, default='', max_length=64)),
                ('normalized_upc', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'label', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDrugSupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('item_number', models.CharField(blank=True, default='', max_length=100)),
                ('pack_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('catalogue_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_multiple', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_preferred', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_preferred', 'supplier_name', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='prescriptiondrug',
            name='uniq_prescription_drug_identity',
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='din',
            field=models.CharField(blank=True, default='', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]{8}$', 'Enter an eight-digit DIN, including any leading zeros.')]),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='dosage_form',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='drug_schedule',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='generic_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Needs review'), ('reviewed', 'Reviewed')], default='unreviewed', max_length=16),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='route',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('ordering_sheet', 'Ordering sheet')], default='manual', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='storage_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrug',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('brand')), django.db.models.functions.text.Lower(django.db.models.functions.text.Replace(django.db.models.functions.text.Trim('strength'), models.Value(' '), models.Value(''))), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('dosage_form')), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('route')), name='uniq_prescription_drug_identity'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrug',
            constraint=models.UniqueConstraint(condition=models.Q(('din', ''), _negated=True), fields=('din',), name='uniq_prescription_drug_din'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrug',
            constraint=models.CheckConstraint(condition=models.Q(('din', ''), ('din__regex', '^[0-9]{8}$'), _connector='OR'), name='prescription_drug_din_format'),
        ),
        migrations.AddField(
            model_name='prescriptiondrugchange',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptiondrugchange',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='app.prescriptiondrug'),
        ),
        migrations.AddField(
            model_name='prescriptiondrugpackage',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='app.prescriptiondrug'),
        ),
        migrations.AddField(
            model_name='prescriptiondrugpackage',
            name='inventory_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_package', to='app.product'),
        ),
        migrations.AddField(
            model_name='prescriptiondrugsupplieritem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_items', to='app.prescriptiondrugpackage'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugpackage',
            constraint=models.UniqueConstraint(models.F('drug'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('label')), name='uniq_prescription_pack_label'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugpackage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gt', 0), _connector='OR'), name='prescription_pack_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugpackage',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_point__isnull', True), ('reorder_point__gte', 0), _connector='OR'), name='prescription_pack_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugpackage',
            constraint=models.CheckConstraint(condition=models.Q(('target_stock__isnull', True), ('target_stock__gte', 0), _connector='OR'), name='prescription_pack_target_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugpackage',
            constraint=models.CheckConstraint(condition=models.Q(('target_stock__isnull', True), ('reorder_point__isnull', True), ('target_stock__gte', models.F('reorder_point')), _connector='OR'), name='prescription_pack_target_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugsupplieritem',
            constraint=models.UniqueConstraint(models.F('package'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('supplier_name')), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('item_number')), name='uniq_prescription_supplier_item'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugsupplieritem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('package',), name='uniq_prescription_pack_preferred'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugsupplieritem',
            constraint=models.CheckConstraint(condition=models.Q(('is_preferred', False), ('is_active', True), _connector='OR'), name='prescription_preferred_active'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugsupplieritem',
            constraint=models.CheckConstraint(condition=models.Q(('pack_cost__isnull', True), ('pack_cost__gte', 0), _connector='OR'), name='prescription_pack_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugsupplieritem',
            constraint=models.CheckConstraint(condition=models.Q(('catalogue_price__isnull', True), ('catalogue_price__gte', 0), _connector='OR'), name='prescription_catalog_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondrugsupplieritem',
            constraint=models.CheckConstraint(condition=models.Q(('order_multiple__gte', 1)), name='prescription_order_multiple_positive'),
        ),
        migrations.RunPython(preserve_existing_catalogue, migrations.RunPython.noop),
    ]
