# Generated by Django 5.2.4 on 2026-09-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_prescription_drug_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondruglearningrecord',
            name='catalogue_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
