# Generated by Django 5.2.4 on 2026-09-09 01:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_recently_purchased_manual_order_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinsession',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='dailyreportarchive',
            options={'ordering': ['-report_date', '-updated_at', '-pk']},
        ),
        migrations.AlterModelManagers(
            name='checkinsession',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='archive_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinsession',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_checkin_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportarchive',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportarchive',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_daily_report_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportarchive',
            name='content_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dailyreportarchive',
            name='snapshot_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='labelsession',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportarchive',
            name='report_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['archived_at', '-started_at'], name='session_archive_started_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportarchive',
            index=models.Index(fields=['report_date', '-updated_at'], name='dailyreport_date_saved_idx'),
        ),
    ]
