param(
    [string]$Reason = "manual",
    [string]$OutputDirectory = "",
    [string]$BusinessDate = "",
    [string]$NotBefore = "",
    [int]$CommandTimeoutSeconds = 0,
    [int]$LockWaitSeconds = 0,
    [switch]$ForceNew,
    [switch]$SelfTest
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$envFile = Join-Path $projectRoot ".env"
$logDirectory = Join-Path $projectRoot "logs"
$logPath = Join-Path $logDirectory "database-backup.log"
New-Item -ItemType Directory -Force -Path $logDirectory | Out-Null

function Read-DotEnv {
    $values = @{}
    if (-not (Test-Path -LiteralPath $envFile)) {
        throw ".env is missing. Database backup cannot determine the connection settings."
    }
    foreach ($line in Get-Content -LiteralPath $envFile) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#") -or -not $trimmed.Contains("=")) {
            continue
        }
        $parts = $trimmed.Split("=", 2)
        $values[$parts[0].Trim()] = $parts[1].Trim().Trim('"').Trim("'")
    }
    return $values
}

function Get-ConfigValue([hashtable]$Config, [string]$Name, [string]$Default = "") {
    if ($Config.ContainsKey($Name) -and $Config[$Name]) { return [string]$Config[$Name] }
    return $Default
}

function Find-PostgresTool([string]$Name, [hashtable]$Config) {
    $configuredBin = Get-ConfigValue $Config "POSTGRESQL_BIN"
    if ($configuredBin) {
        $candidate = Join-Path $configuredBin "$Name.exe"
        if (Test-Path -LiteralPath $candidate) { return $candidate }
    }

    $command = Get-Command $Name -ErrorAction SilentlyContinue
    if ($command) { return $command.Source }

    $roots = @(Get-ChildItem -LiteralPath "C:\Program Files\PostgreSQL" -Directory -ErrorAction SilentlyContinue |
        Sort-Object { try { [version]$_.Name } catch { [version]"0.0" } } -Descending)
    foreach ($root in $roots) {
        $candidate = Join-Path $root.FullName "bin\$Name.exe"
        if (Test-Path -LiteralPath $candidate) { return $candidate }
    }
    throw "$Name was not found. Set POSTGRESQL_BIN in .env to PostgreSQL's bin folder."
}

function Resolve-PositiveSetting(
    [int]$ExplicitValue,
    [hashtable]$Config,
    [string]$Name,
    [int]$DefaultValue,
    [int]$MinimumValue,
    [int]$MaximumValue
) {
    if ($ExplicitValue -gt 0) {
        $value = $ExplicitValue
    }
    else {
        $rawValue = Get-ConfigValue $Config $Name ([string]$DefaultValue)
        $value = 0
        if (-not [int]::TryParse($rawValue, [ref]$value)) {
            throw "$Name must be a whole number."
        }
    }
    if ($value -lt $MinimumValue -or $value -gt $MaximumValue) {
        throw "$Name must be between $MinimumValue and $MaximumValue seconds."
    }
    return $value
}

function ConvertTo-ProcessArgument([string]$Value) {
    if ($Value -notmatch '[\s"]') {
        return $Value
    }
    # PostgreSQL arguments generated by this script never contain a literal
    # quote. Quoting the complete value preserves paths containing spaces when
    # Windows PowerShell joins Start-Process's ArgumentList.
    return '"' + $Value.Replace('"', '\"') + '"'
}

function Invoke-PostgresCommand(
    [string]$FilePath,
    [string[]]$Arguments,
    [int]$TimeoutSeconds,
    [string]$Label
) {
    $process = $null
    $stdoutTask = $null
    $stderrTask = $null
    $startedAt = Get-Date
    $nextProgressAt = $startedAt.AddSeconds(10)
    $outputPath = ""
    try {
        $quotedArguments = @($Arguments | ForEach-Object {
            ConvertTo-ProcessArgument ([string]$_)
        })

        # Start-Process on Windows PowerShell 5.1 can return a Process object
        # whose ExitCode is null when stdout/stderr are redirected. That is the
        # exact host used by production.bat and made successful dumps look like
        # `pg_dump failed with exit code .`. Starting the process through .NET
        # gives us one stable process handle and exit code on both Windows
        # PowerShell 5.1 and PowerShell 7.
        $startInfo = New-Object System.Diagnostics.ProcessStartInfo
        $startInfo.FileName = $FilePath
        $startInfo.Arguments = ($quotedArguments -join " ")
        $startInfo.UseShellExecute = $false
        $startInfo.CreateNoWindow = $true
        $startInfo.RedirectStandardOutput = $true
        $startInfo.RedirectStandardError = $true

        $process = New-Object System.Diagnostics.Process
        $process.StartInfo = $startInfo
        if (-not $process.Start()) {
            throw "$Label could not be started."
        }
        foreach ($argument in $Arguments) {
            if ([string]$argument -like "--file=*") {
                $outputPath = ([string]$argument).Substring(7)
                break
            }
        }
        Write-Host (
            "$Label started (PID $($process.Id)); timeout is " +
            "$TimeoutSeconds seconds."
        ) -ForegroundColor DarkGray
        # Drain both streams asynchronously so a verbose PostgreSQL error can
        # never fill one pipe and deadlock the process while we wait on it.
        $stdoutTask = $process.StandardOutput.ReadToEndAsync()
        $stderrTask = $process.StandardError.ReadToEndAsync()

        $deadline = $startedAt.AddSeconds($TimeoutSeconds)
        $completed = $false
        while ((Get-Date) -lt $deadline) {
            if ($process.WaitForExit(1000)) {
                $completed = $true
                break
            }
            $now = Get-Date
            if ($now -ge $nextProgressAt) {
                $elapsedSeconds = [int][Math]::Floor(($now - $startedAt).TotalSeconds)
                $progressDetail = ""
                if ($outputPath -and (Test-Path -LiteralPath $outputPath)) {
                    $writtenMb = (Get-Item -LiteralPath $outputPath).Length / 1MB
                    $progressDetail = "; {0:N1} MB written" -f $writtenMb
                }
                Write-Host (
                    "$Label is still running: $elapsedSeconds seconds elapsed" +
                    "$progressDetail."
                ) -ForegroundColor DarkGray
                $nextProgressAt = $now.AddSeconds(10)
            }
        }

        if (-not $completed) {
            $timedOutPid = $process.Id
            $taskkill = Join-Path $env:SystemRoot "System32\taskkill.exe"
            try {
                & $taskkill @("/PID", $timedOutPid, "/T", "/F") 2>&1 | Out-Null
            }
            catch {
                # The exact process was created above. Stop-Process is a safe
                # final fallback if taskkill itself is unavailable.
            }
            try {
                $process.Refresh()
                if (-not $process.HasExited) {
                    Stop-Process -Id $timedOutPid -Force -ErrorAction SilentlyContinue
                }
            }
            catch {
                # The process may have exited between Refresh and inspection.
            }
            throw "$Label timed out after $TimeoutSeconds seconds; its process tree was terminated."
        }

        # The parameterless wait ensures redirected file handles are flushed.
        $process.WaitForExit()
        $exitCode = [int]$process.ExitCode
        $stdout = $stdoutTask.GetAwaiter().GetResult()
        $stderr = $stderrTask.GetAwaiter().GetResult()
        return [pscustomobject]@{
            ExitCode = $exitCode
            Stdout = [string]$stdout
            Stderr = [string]$stderr
        }
    }
    finally {
        if ($null -ne $process) {
            $process.Dispose()
        }
    }
}

function Get-Sha256FileHash([string]$Path) {
    # Get-FileHash is provided by Microsoft.PowerShell.Utility, which may not
    # be discoverable when this script inherits a reduced PSModulePath from a
    # launcher. The .NET fallback keeps verified backups available everywhere.
    $fileHashCommand = Get-Command Get-FileHash -ErrorAction SilentlyContinue
    if ($fileHashCommand) {
        return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
    }

    $stream = [IO.File]::OpenRead($Path)
    $sha256 = [Security.Cryptography.SHA256]::Create()
    try {
        $bytes = $sha256.ComputeHash($stream)
        return ([BitConverter]::ToString($bytes)).Replace("-", "").ToLowerInvariant()
    }
    finally {
        $sha256.Dispose()
        $stream.Dispose()
    }
}

function Test-VerifiedBackup(
    [string]$Path,
    [string]$PgRestore,
    [int]$TimeoutSeconds
) {
    $candidateChecksumPath = "$Path.sha256"
    if (-not (Test-Path -LiteralPath $candidateChecksumPath)) {
        return $false
    }

    try {
        $checksumRecord = (Get-Content -LiteralPath $candidateChecksumPath -Raw).Trim()
        $expectedHash = ($checksumRecord -split '\s+')[0].ToLowerInvariant()
        if ($expectedHash -notmatch '^[a-f0-9]{64}$') {
            return $false
        }
        if ((Get-Sha256FileHash $Path) -ne $expectedHash) {
            return $false
        }

        $verification = Invoke-PostgresCommand `
            -FilePath $PgRestore `
            -Arguments @("--list", $Path) `
            -TimeoutSeconds $TimeoutSeconds `
            -Label "pg_restore verification"
        return $verification.ExitCode -eq 0
    }
    catch {
        return $false
    }
}

$config = Read-DotEnv
$databaseName = Get-ConfigValue $config "DB_NAME" "postgres"
$databaseUser = Get-ConfigValue $config "DB_USER" "postgres"
$databaseHost = Get-ConfigValue $config "DB_HOST" "127.0.0.1"
$databasePort = Get-ConfigValue $config "DB_PORT" "5432"
$databasePassword = Get-ConfigValue $config "DB_PASSWORD"
if (-not $databasePassword) {
    throw (
        "DB_PASSWORD is missing from .env. Open production.bat and choose Start; " +
        "the production console will securely prompt for it once."
    )
}
$CommandTimeoutSeconds = Resolve-PositiveSetting `
    $CommandTimeoutSeconds $config `
    "PHARMACY_BACKUP_COMMAND_TIMEOUT_SECONDS" 600 30 3600
$LockWaitSeconds = Resolve-PositiveSetting `
    $LockWaitSeconds $config `
    "PHARMACY_BACKUP_LOCK_WAIT_SECONDS" 30 1 600
$retentionDaysRaw = Get-ConfigValue $config "PHARMACY_BACKUP_RETENTION_DAYS" "30"
$retentionDays = 30
if (-not [int]::TryParse($retentionDaysRaw, [ref]$retentionDays) -or $retentionDays -lt 1) {
    throw "PHARMACY_BACKUP_RETENTION_DAYS must be a positive whole number."
}

if (-not $OutputDirectory) {
    $OutputDirectory = Get-ConfigValue $config "PHARMACY_BACKUP_DIR" "backups\database"
}
if (-not [IO.Path]::IsPathRooted($OutputDirectory)) {
    $OutputDirectory = Join-Path $projectRoot $OutputDirectory
}
New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
$backupDirectory = (Resolve-Path -LiteralPath $OutputDirectory).Path

$backupLockPath = Join-Path $backupDirectory ".pharmacy-backup.lock"
$backupOwnerPath = Join-Path $backupDirectory ".pharmacy-backup.owner.json"
$backupLockStream = $null
$lockDeadline = (Get-Date).AddSeconds($LockWaitSeconds)
$lastLockError = $null
do {
    try {
        # An exclusive file handle coordinates Task Scheduler, production
        # startup, and manual backups. The empty file may persist; only the
        # held handle is the lock. A short bounded wait absorbs normal overlap
        # with an almost-complete scheduled backup.
        $backupLockStream = [IO.File]::Open(
            $backupLockPath,
            [IO.FileMode]::OpenOrCreate,
            [IO.FileAccess]::ReadWrite,
            [IO.FileShare]::None
        )
    }
    catch [IO.IOException] {
        $lastLockError = $_.Exception
        if ((Get-Date) -lt $lockDeadline) {
            Start-Sleep -Seconds 1
        }
    }
} while ($null -eq $backupLockStream -and (Get-Date) -lt $lockDeadline)

if ($null -eq $backupLockStream) {
    $ownerHint = ""
    try {
        if (Test-Path -LiteralPath $backupOwnerPath) {
            $owner = Get-Content -LiteralPath $backupOwnerPath -Raw |
                ConvertFrom-Json
            if ($owner.process_id) {
                $ownerHint = (
                    " Holder PID: $($owner.process_id); started: " +
                    "$($owner.started_at); reason: $($owner.reason)."
                )
            }
        }
    }
    catch {
        # Owner metadata is diagnostic only; the file handle is authoritative.
    }
    $message = (
        "Database backup lock remained busy for $LockWaitSeconds seconds at " +
        "$backupLockPath.$ownerHint Stop the recorded backup process or " +
        "reboot before retrying; do not delete the lock file while it is held."
    )
    if ($null -ne $lastLockError -and -not $ownerHint) {
        $message += " Windows reported: $($lastLockError.Message)"
    }
    Add-Content -LiteralPath $logPath -Value "$(Get-Date -Format o) FAILED $message"
    throw $message
}

try {
$ownerRecord = [ordered]@{
    process_id = $PID
    started_at = (Get-Date -Format o)
    reason = $Reason
    command_timeout_seconds = $CommandTimeoutSeconds
}
try {
    $ownerRecord | ConvertTo-Json -Compress |
        Set-Content -LiteralPath $backupOwnerPath -Encoding UTF8
}
catch {
    # Diagnostics must never prevent a verified backup.
}
$pgDump = Find-PostgresTool "pg_dump" $config
$pgRestore = Find-PostgresTool "pg_restore" $config

if ($SelfTest) {
    # Reaching this point proves that the task identity can read .env, resolve
    # and write the configured output directory, take the cross-process lock,
    # and locate both PostgreSQL tools. Do not connect to PostgreSQL or create a
    # dump; the Django half of the runner self-test validates the live database.
    Write-Host "Database backup prerequisites are available." -ForegroundColor Green
    Write-Output $backupDirectory
    return
}

$safeReason = ($Reason -replace '[^A-Za-z0-9_-]', '-').Trim('-')
if (-not $safeReason) { $safeReason = "manual" }

$scheduledDayToken = Get-Date -Format "yyyyMMdd"
$minimumCandidateTime = $null
if ($BusinessDate) {
    $parsedBusinessDate = [datetime]::MinValue
    if (-not [datetime]::TryParseExact(
        $BusinessDate,
        "yyyy-MM-dd",
        [Globalization.CultureInfo]::InvariantCulture,
        [Globalization.DateTimeStyles]::None,
        [ref]$parsedBusinessDate
    )) {
        throw "BusinessDate must use YYYY-MM-DD format."
    }
    $scheduledDayToken = $parsedBusinessDate.ToString("yyyyMMdd")
}
if ($NotBefore) {
    $parsedNotBefore = [DateTimeOffset]::MinValue
    if (-not [DateTimeOffset]::TryParse(
        $NotBefore,
        [Globalization.CultureInfo]::InvariantCulture,
        [Globalization.DateTimeStyles]::RoundtripKind,
        [ref]$parsedNotBefore
    )) {
        throw "NotBefore must be an ISO-8601 timestamp."
    }
    $minimumCandidateTime = $parsedNotBefore.LocalDateTime
}

# A database-backed scheduled job may safely retry the same business date.
# Reuse that day's backup only after re-validating both its checksum and its
# PostgreSQL archive structure. Missing/corrupt artifacts are deliberately not
# treated as success, so a retry creates a fresh backup.
if ($safeReason -ieq "scheduled" -and -not $ForceNew) {
    $scheduledCandidates = @(
        Get-ChildItem -LiteralPath $backupDirectory `
            -Filter "pharmacy-$scheduledDayToken-*-scheduled.dump" -File `
            -ErrorAction SilentlyContinue |
            Where-Object {
                $null -eq $minimumCandidateTime -or
                $_.LastWriteTime -ge $minimumCandidateTime
            } |
            Sort-Object LastWriteTime -Descending
    )
    foreach ($candidate in $scheduledCandidates) {
        if (Test-VerifiedBackup `
            $candidate.FullName $pgRestore $CommandTimeoutSeconds
        ) {
            Write-Host "Scheduled database backup already verified: $($candidate.FullName)" -ForegroundColor Green
            Add-Content -LiteralPath $logPath -Value "$(Get-Date -Format o) SKIPPED verified same-day scheduled backup $($candidate.FullName)"
            Write-Output $candidate.FullName
            return
        }
        Add-Content -LiteralPath $logPath -Value "$(Get-Date -Format o) RETRY ignored unverified same-day scheduled backup $($candidate.FullName)"
    }
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
if ($safeReason -ieq "scheduled" -and $BusinessDate) {
    $timestamp = "$scheduledDayToken-$(Get-Date -Format 'HHmmss')"
}
$finalPath = Join-Path $backupDirectory "pharmacy-$timestamp-$safeReason.dump"
$temporaryPath = "$finalPath.partial"
$checksumPath = "$finalPath.sha256"
$previousPgPassword = [Environment]::GetEnvironmentVariable("PGPASSWORD", "Process")

try {
    [Environment]::SetEnvironmentVariable("PGPASSWORD", $databasePassword, "Process")
    $dumpResult = Invoke-PostgresCommand `
        -FilePath $pgDump `
        -Arguments @(
            "--host=$databaseHost", "--port=$databasePort",
            "--username=$databaseUser", "--dbname=$databaseName",
            "--format=custom", "--compress=9", "--no-owner", "--no-acl", "--no-password",
            "--file=$temporaryPath"
        ) `
        -TimeoutSeconds $CommandTimeoutSeconds `
        -Label "pg_dump"
    if ($dumpResult.ExitCode -ne 0) {
        $dumpError = ([string]$dumpResult.Stderr -replace '\s+$', '').Trim()
        $message = "pg_dump failed with exit code $($dumpResult.ExitCode)."
        if ($dumpError) { $message += " $dumpError" }
        throw $message
    }
    if (-not (Test-Path -LiteralPath $temporaryPath) -or (Get-Item -LiteralPath $temporaryPath).Length -eq 0) {
        throw "pg_dump did not create a usable backup file."
    }

    $restoreResult = Invoke-PostgresCommand `
        -FilePath $pgRestore `
        -Arguments @("--list", $temporaryPath) `
        -TimeoutSeconds $CommandTimeoutSeconds `
        -Label "pg_restore verification"
    if ($restoreResult.ExitCode -ne 0) {
        $restoreError = ([string]$restoreResult.Stderr -replace '\s+$', '').Trim()
        $message = (
            "Backup verification failed with exit code " +
            "$($restoreResult.ExitCode)."
        )
        if ($restoreError) { $message += " $restoreError" }
        throw $message
    }

    Move-Item -LiteralPath $temporaryPath -Destination $finalPath
    $hash = Get-Sha256FileHash $finalPath
    Set-Content -LiteralPath $checksumPath -Value "$hash  $([IO.Path]::GetFileName($finalPath))" -Encoding ASCII

    $cutoff = (Get-Date).AddDays(-$retentionDays)
    Get-ChildItem -LiteralPath $backupDirectory -Filter "pharmacy-*.dump" -File |
        Where-Object { $_.LastWriteTime -lt $cutoff } |
        ForEach-Object {
            $expiredBackup = $_.FullName
            $expiredChecksum = "$expiredBackup.sha256"
            Remove-Item -LiteralPath $expiredBackup -Force
            if (Test-Path -LiteralPath $expiredChecksum) {
                Remove-Item -LiteralPath $expiredChecksum -Force
            }
        }

    Write-Host "Database backup verified: $finalPath" -ForegroundColor Green
    Add-Content -LiteralPath $logPath -Value "$(Get-Date -Format o) OK $finalPath"
    Write-Output $finalPath
}
catch {
    Add-Content -LiteralPath $logPath -Value "$(Get-Date -Format o) FAILED $($_.Exception.Message)"
    throw
}
finally {
    [Environment]::SetEnvironmentVariable("PGPASSWORD", $previousPgPassword, "Process")
    if (Test-Path -LiteralPath $temporaryPath) {
        Remove-Item -LiteralPath $temporaryPath -Force
    }
}
}
finally {
    try {
        if (Test-Path -LiteralPath $backupOwnerPath) {
            $record = Get-Content -LiteralPath $backupOwnerPath -Raw |
                ConvertFrom-Json
            if ([int]$record.process_id -eq $PID) {
                Remove-Item -LiteralPath $backupOwnerPath -Force
            }
        }
    }
    catch {
        # Stale diagnostic metadata is replaced by the next lock owner.
    }
    if ($null -ne $backupLockStream) {
        $backupLockStream.Dispose()
    }
}
